### ISSUE TITLE
Papers to discuss on 29/10/24

### ISSUE THREAD

**Issue by TomHigginson** [astro-group-bristol/black-hole-journal-club#7]
I have come across some interesting papers in arxiv:

Evidence of a toroidal magnetic field in the core of 3C82 - [Paraschos+2024](https://arxiv.org/pdf/2405.00097)

Do all the quasars and high-excitation radio galaxies (HERGs) in the 3CRR catalog contain a magnetically arrested disk (MAD)? - [Li+2024](https://arxiv.org/pdf/2408.00321)

Probing the high frequency variability of NGC 5044: the key to AGN feedback - [Schellenberger+2024](https://arxiv.org/pdf/2409.06039)

Spectral index variation across X-shaped radio galaxies - [Petra+2023](https://arxiv.org/pdf/2306.17229)

**Comment by fjebaker** [comment]
There's also this cool paper by Mitch Begelman on globally magnetised disc solutions:
http://arxiv.org/abs/2402.15657

I started reading it but haven't had the chance to finish it yet! Will try to before the meeting.

**Comment by phajy** [comment]
[Joining the Dots: High Redshift Black holes](https://arxiv.org/abs/2410.16970) by Andrew King.

**Comment by fjebaker** [comment]
[Amoeba: An AGN Model of Optical Emissions Beyond steady-state Accretion discs](http://arxiv.org/abs/2410.19630) by Henry Best (we saw a preview of this work at the Naples conference in 2023)

**Comment by fjebaker** [comment]
https://eventhorizontelescope.org/blog/response-independent-analysis-ehtc-imaging-sgr-miyoshi-et-al-2024
